knpu_oauth2_client:
    clients:
        2le_oauth:
            type: generic

            provider_class: Lle\OAuthClientBundle\Provider\LleProvider
            provider_options: {domain: '%env(DOMAIN)%'}

            client_id: '%env(CLIENT_ID)%'
            client_secret: '%env(CLIENT_SECRET)%'
            redirect_route: login_check

lle_oauth_client:
    domain: '%env(DOMAIN)%'