easy_admin:
    translation_domain: messages
    formats:
        datetime: 'd/m/Y à H\hi'
        date: d/m/Y
        time: 'H\hi e'
    site_name: 'Admin'
    design:
        templates:
            layout: 'easy_admin/layout.html.twig'
        brand_color: '#009DDD'
        form_theme: []
        assets:
            css:
                - '/bundles/lleeasyadminplus/css/lle-easyadmin-plus.css'
            favicon:
                path: 'logo.png'

